docs/UserGuide.md
Updated the delete section of userguide.
Merging this closes #6
=> Update Userguide for delete

docs/UserGuide.md
I have removed the image referencing to `images/findAlexDavidResult.png` since it does not match the commands given in the example and we might have a slightly different looking UI down the road. Should we delete this file then?
I also took this chance to update some other parts of the user guide to match our project and remove additional traces of AB3.
Merging this closes #7
=> Update user guide for find

docs/AboutUs.md, docs/team/ngzixuan.md
Add member details into About.md in Docs
=> Add member Ng Zi Xuan details into docs

docs/UserGuide.md
=> Update Add and Details in UserGuide.md 

docs/UserGuide.md
For now, our clear feature will only have `clear ALL ENTRIES`
We might want to add an additional layer of confirmation when we implement the feature
e.g. Are you sure you want to clear all entries? YES / NO
=> Update clear in UserGuide.md

docs/UserGuide.md
Updated the list section of the User Guide.
Merging this closes #8
=> Update User Guide for list

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/DetailsCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DetailsCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/person/NameEqualKeywordPredicate.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonDetailsCard.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/resources/view/PersonDetailsCard.fxml, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/DetailsCommandTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DetailsCommandParserTest.java, src/test/java/seedu/address/model/person/NameEqualKeywordPredicateTest.java
Although the UI looks very similar to the `find` command, the `details` command uses the `PersonDetailsCard` component while the `find` command uses the `PersonListCard` component (Notice it says Alex Yeoh details here in the card). The person object is available as the parameter of the `PersonDetailsCard` so the UI is easily and highly customizable. I'll leave this to the person working on the UI.
The `details` command also requires a case sensitive, exact match with the name (and only checks for the name) while the `find` command checks for more fields and does not require exact match.
Merging this closes #32
=> Implement details command

src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml
Shortened height of cards to enhance the visibility of multiple person objects. 
Merging this will close issue #36
=> Remove excess details from list view cards

src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml
Having worked with the UI components for the details command, I believe a tab feature is the best course of action forward. The way AB3 is structured makes it hard to update the view with command. Notice how logic does not manipulate Ui, but manipulates model which Ui depends on. An easy way to keep this design intact is to have multiple views. With multiple views, our Logic and manipulate the model and thus the Ui indirectly, rather than conditionally rendering the view base on the command type (this happened to be an issue, see #47 ).
The tab feature enables us to place multiple views on the screen.
This closes #49
=> Tab feature

src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/event/EventName.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/model/event/EventNameTest.java, src/test/java/seedu/address/model/event/EventTest.java, src/test/java/seedu/address/testutil/EventBuilder.java, src/test/java/seedu/address/testutil/TypicalEvents.java
This implements the model component of the event feature.
This closes #51.
=> Implement event tracking feature

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/ChainCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/commands/ChainCommandTest.java, src/test/java/seedu/address/logic/commands/ClearCommandTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Part 1 of Advanced Commands 
Chaining of multiple commands
=> Branch chain command

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/HelpCommand.java
I thought about this for quite a bit last night. I believe that regardless, we will have the same issue when working with events. It would be better to document this behavior since it is not exactly an unwanted behavior, although admittedly somewhat unexpected behavior.
=> Update documentation on behavior related to consecutive commands with details and help

docs/DeveloperGuide.md, src/main/java/seedu/address/logic/commands/ClearCommand.java
As in title
This should close #107
=> Revert changes to DeveloperGuide.md

docs/UserGuide.md, src/main/java/seedu/address/model/UserPrefs.java
Change JSON file name to foryourinterest.json
This should close #99 
Note that for this change to take effect, you should delete preferences.json on your local machine.
=> Change JSON file name

build.gradle, docs/DeveloperGuide.md, docs/UserGuide.md
Fixes #93 #126 #120 #110 #104 #100 #99 #95 #96
=> Fix bugs found in PED

docs/UserGuide.md
=> Document #114

src/main/java/seedu/address/logic/commands/RemovePersonFromEventCommand.java
Fix bug where removePersonFromEvent command was removing the wrong person.
Closes #133 #127
=> Fix RemovePersonFromEventCommand

docs/UserGuide.md
Fix documentation bugs for add and edit in UG
Closes #129 #132 #117 #119 #112 #109 #106 #97 #101 #102
=> Fix documentation bugs for add and edit in UG

src/main/java/seedu/address/model/person/Telegram.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
Update telegram to disallow handles with spaces
=> Branch bug fix telegram

docs/UserGuide.md
=> Fixed formatting for delete in command summary.

src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Fixed issue with "&&" in telegram not accepted due to chain command implementation. 
Merging will close #113 #125 #118 #113
=> Fix for chain command and t/ issue
